name: podcast_search
description: A library for searching for podcasts (via iTunes), parsing podcast RSS feeds and obtaining episodes details.

version: 0.3.7
homepage: https://github.com/amugofjava/podcast_search

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  # Dio HTTP client.
  dio: ^3.0.9

  # RSS parsing library.
  dart_rss: ^1.1.0

  # Meta.
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
