name: podcast_search
description: A library for searching for podcasts and parsing podcast RSS feeds. Supports iTunes and PodcastIndex directories, and newer features such as chapters and transcripts.

version: 0.7.11
homepage: https://github.com/amugofjava/podcast_search

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  convert: ^3.1.2
  crypto: ^3.0.1
  dio: ^5.8.0+1
  intl: ^0.20.2
  rss_dart: ^1.0.13
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.26.2

funding:
  - https://github.com/sponsors/amugofjava
  - https://ko-fi.com/amugofjava
