name: podcast_search
description: A library for searching for podcasts, parsing podcast RSS feeds and obtaining episodes details. Supports searching via iTunes and PodcastIndex (preview).

version: 0.4.0
homepage: https://github.com/amugofjava/podcast_search

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  archive: ^3.1.2
  convert: ^3.0.0
  crypto: ^3.0.0
  dio: ^4.0.0-prev3
  # dart_rss: ^1.1.1+1
  # Temporarily use custom fork required for podcast namespace.
  dart_rss:
    git: https://github.com/amugofjava/dart-rss
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
