name: podcast_search
description: A library for searching for podcasts (via iTunes), parsing podcast RSS feeds and obtaining episodes details.

version: 0.3.4
homepage: https://github.com/amugofjava/podcast_search

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  # Dio HTTP client.
  dio: ^3.0.9

  # RSS parsing library.
  # I dislike pulling in directly from Git, but until the parent package is
  # updated I need this commit as it contains a necessary dependency update.
  dart_rss:
    git:
      url: https://github.com/amugofjava/dart-rss.git
      ref: 2ad380dd84f5d2b32acabac226999086945273ab

  # Meta.
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
